
(function(){
  const form = $('#ts-form'), tbody = $('#ts-table tbody');
  function view(r){
    const b = el('div',{},
      el('h3',{}, `Timesheet #${r.id}`),
      el('div',{class:'print-receipt'},
        el('div',{}, el('strong',{}, 'Employee: '), r.employee),
        el('div',{}, el('strong',{}, 'Department: '), r.department),
        el('div',{}, el('strong',{}, 'Period: '), r.period),
        el('div',{}, el('strong',{}, 'Hours: '), String(r.totalHours)),
        el('div',{}, el('strong',{}, 'Status: '), r.status)
      ),
      el('div',{class:'small'}, 'Generated by SmartTIME (demo)'),
      el('div',{}, el('button',{onclick:()=>window.print(), class:'secondary'}, 'Print'),' ', el('button',{class:'ghost',onclick:modal.close}, 'Close'))
    ); modal.open(b);
  }
  function row(r){
    return el('tr',{},
      el('td',{}, String(r.id)),
      el('td',{}, r.employee),
      el('td',{}, r.department),
      el('td',{}, r.period),
      el('td',{}, String(r.totalHours)),
      el('td',{}, el('span',{class:'badge '+(r.status==='Approved'?'ok':'info')}, r.status)),
      el('td',{}, el('button',{class:'ghost',onclick:()=>view(r)}, 'View/Print'))
    );
  }
  function render(){ tbody.innerHTML=''; SmartTown.getAll('timesheets').forEach(r=>tbody.appendChild(row(r))); }
  form.addEventListener('submit', (e)=>{
    e.preventDefault();
    const rec = { employee:$('#emp').value.trim(), department:$('#dept').value.trim(), period:$('#period').value.trim(),
      totalHours:Number($('#hours').value||0), notes:$('#notes').value.trim(), status:'Submitted' };
    SmartTown.upsert('timesheets', rec); toast('Timesheet submitted'); form.reset(); render();
  });
  render();
})();
