
(function(){
  const form = $('#ap-form'), linesTbody = $('#ap-lines tbody'), totalEl = $('#ap-total'), tableBody = $('#ap-table tbody');
  const buf = []; const fmt = (n)=>formatCurrency(n||0);

  function receipt(rec){
    const html = `<div class="print-receipt">
      <h2 style="margin:0 0 8px 0">AP Turnover Receipt</h2>
      <div><strong>Warrant: </strong>${rec.warrant}</div>
      <div><strong>Department: </strong>${rec.dept}</div>
      <div><strong>Submitted By: </strong>${rec.submittedBy}</div>
      <div><strong>Total: </strong>${fmt(rec.total)}</div>
      <div><strong>Items: </strong>${rec.items}</div>
      <div class="small">Generated by SmartFISCAL (demo)</div>
    </div>`;
    modal.open(html);
  }

  function redrawLines(){
    linesTbody.innerHTML=''; let tot = 0;
    buf.forEach((r,i)=>{
      tot += Number(r.amount||0);
      linesTbody.appendChild(el('tr',{},
        el('td',{}, r.vendor||'-'),
        el('td',{}, r.desc||'-'),
        el('td',{}, fmt(r.amount)),
        el('td',{}, el('button',{class:'ghost',onclick:()=>{buf.splice(i,1); redrawLines();}}, 'Remove'))
      ));
    });
    totalEl.textContent = fmt(tot);
  }

  $('#add').addEventListener('click', ()=>{
    const r = {vendor:$('#vendor').value.trim(), desc:$('#desc').value.trim(), amount:Number($('#amount').value||0)};
    if(!r.vendor && !r.amount){ toast('Add at least a vendor & amount','warn'); return; }
    buf.push(r); $('#vendor').value=$('#desc').value=$('#amount').value=''; redrawLines();
  });
  $('#clear').addEventListener('click', ()=>{ buf.splice(0,buf.length); redrawLines(); });

  form.addEventListener('submit', (e)=>{
    e.preventDefault();
    if(buf.length===0){ toast('Add at least one line','warn'); return; }
    const total = buf.reduce((s,r)=>s+Number(r.amount||0),0);
    const rec = { dept:$('#dept').value.trim(), warrant:$('#warrant').value.trim(), submittedBy:$('#submitted').value.trim(),
      items:buf.length, total:total, status:'Received' };
    SmartTown.upsert('ap_turnovers', rec);
    buf.splice(0,buf.length); redrawLines(); form.reset(); toast('Turnover saved'); render();
    receipt(rec);
  });

  function render(){
    tableBody.innerHTML='';
    SmartTown.getAll('ap_turnovers').forEach(r=>{
      tableBody.appendChild(el('tr',{},
        el('td',{}, String(r.id)),
        el('td',{}, r.warrant),
        el('td',{}, r.dept),
        el('td',{}, String(r.items)),
        el('td',{}, fmt(r.total)),
        el('td',{}, el('span',{class:'badge'}, r.status))
      ));
    });
  }
  redrawLines(); render();
})();
