(function(){const rand=a=>a[Math.floor(Math.random()*a.length)];const statuses=['Open','In Progress','Completed'];
const first=['River','Juniper','Cedar','Maple','Echo','Skylar','Taylor','Rowan','Casey','Quinn','Avery','Sage'];
const last=['Ridge','Hollow','Spruce','Pike','Meadow','Brook','Frost','Finch','Wren','Vale'];
const roads=['Depot Rd','Center St','Old Mill Rd','Maple Lane','Sunset Way','Barn View Ave'];
const SEED={issues:[{id:1,createdAt:Date.now()-86400000*2,type:"Pothole",desc:"Crater-size pothole by the feed store",location:"Elm St @ 2nd",status:"Open",contact:"spruce@example.town"},{id:2,createdAt:Date.now()-86400000,type:"Streetlight",desc:"Lamp flickers like a strobe near the library",location:"Main St",status:"In Progress",contact:"anon@nowhere.tld"}],licenses:[{id:1,createdAt:Date.now()-86400000,type:"Common Victualler",business:"Lucky Lantern Cafe",applicant:"Skylar Pike",status:"Pending",notes:"Awaiting Fire sign-off"},{id:2,createdAt:Date.now()-43200000,type:"Peddler",business:"Hollow Creek Honey",applicant:"River Vale",status:"Approved",notes:"expires 12/31"}],ap_turnovers:[{id:1,warrant:"FY26-001",dept:"DPW",submittedBy:"Clerk Team",total:12500.43,items:3,status:"Received",createdAt:Date.now()-172800000}],timesheets:[{id:1,employee:"Taylor Ridge",department:"Clerk",period:"2025-08-18 to 2025-08-31",totalHours:80,status:"Submitted",createdAt:Date.now()-259200000}],agenda_requests:[{id:1,board:"Select Board",meeting:"2025-09-09 19:00",title:"Road Acceptance – Pine Ridge",requester:"Casey Quill",status:"Under Review"}],documents:[{id:1,title:"FY26 Budget Snapshot",dept:"Finance",tags:["budget","FY26"],url:"#",summary:"High-level rollups with departments.",retention:"Active"},{id:2,title:"ADA Transition Plan — One Pager",dept:"Administration",tags:["ADA","plan"],url:"#",summary:"Executive summary for the board.",retention:"Active"},{id:3,title:"DPW Winter Ops SOP",dept:"DPW",tags:["SOP","winter"],url:"#",summary:"Routes, storm levels, and comms.",retention:"Archive"}],contacts:[{id:1,name:"Sammy Spruce",role:"Exec Assistant",email:"sammy@town.example"},{id:2,name:"Riley Brook",role:"Admin Services",email:"riley@town.example"}]};
for(let i=3;i<=12;i++){const who=rand(first)+' '+rand(last);SEED.issues.push({id:i,createdAt:Date.now()-86400000*Math.random()*10,type:rand(["Pothole","Tree/Brush","Facilities: Building","Sign/Signal"]),desc:"Auto-seeded demo record • reported by "+who,location:rand(roads),status:rand(statuses),contact:"anon@demo.town"});}
const KEY="smarttown_sandbox_v4";const state={load(){const raw=localStorage.getItem(KEY);if(!raw){localStorage.setItem(KEY,JSON.stringify(SEED));return JSON.parse(JSON.stringify(SEED));}try{return JSON.parse(raw);}catch(e){return JSON.parse(JSON.stringify(SEED));}},save(d){localStorage.setItem(KEY,JSON.stringify(d));}};
function getAll(c){return (state.load()[c]||[]).slice().sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));}
function upsert(c,o){const db=state.load();db[c]=db[c]||[];if(!o.id){o.id=1+db[c].reduce((m,x)=>x.id>m?x.id:m,0);if(!o.createdAt)o.createdAt=Date.now();db[c].push(o);}else{const i=db[c].findIndex(x=>x.id===o.id);if(i>-1)db[c][i]={...db[c][i],...o};else db[c].push(o);}state.save(db);return o;}
function remove(c,id){const db=state.load();db[c]=(db[c]||[]).filter(x=>x.id!==id);state.save(db);}
function reset(){localStorage.removeItem(KEY);}
function stats(){const db=state.load();return {issues:db.issues.length,licenses:db.licenses.length,ap_turnovers:db.ap_turnovers.length,timesheets:db.timesheets.length,agenda_requests:db.agenda_requests.length};}
window.SmartTown={getAll,upsert,remove,reset,stats};})();