window.$=(s,r=document)=>r.querySelector(s);window.$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
window.el=(t,a={},...c)=>{const n=document.createElement(t);for(const[k,v]of Object.entries(a||{})){if(k.startsWith("on")&&typeof v==="function"){n.addEventListener(k.slice(2),v);}else if(k==="html"){n.innerHTML=v;}else{n.setAttribute(k,v);}}for(const x of c){if(x!=null)n.appendChild(typeof x==="string"?document.createTextNode(x):x);}return n;};
window.formatCurrency=n=>Number(n||0).toLocaleString(undefined,{style:"currency",currency:"USD"});
window.niceDate=(d=new Date())=>{try{return new Date(d).toLocaleString();}catch(e){return String(d);}};
window.toast=(m,t="info")=>{const b=el("div",{class:"card no-print",style:"position:fixed;right:12px;bottom:12px;z-index:9999;max-width:360px;border-left:4px solid var(--accent)"});b.append(el("div",{class:"kicker"},t.toUpperCase()),el("div",{},m));document.body.appendChild(b);setTimeout(()=>b.remove(),2200);};
window.modal={open(c){let m=$('.modal');if(!m){m=el('div',{class:'modal',id:'__modal'},el('div',{class:'box'}));document.body.appendChild(m);}$('.box',m).innerHTML="";$('.box',m).append(typeof c==="string"?el('div',{html:c}):c);m.style.display='flex';m.addEventListener('click',e=>{if(e.target===m)modal.close();});},close(){const m=$('.modal');if(m)m.style.display='none';}};
window.theme={toggle(){document.documentElement.classList.toggle('dark');localStorage.setItem("smarttown_theme",document.documentElement.classList.contains('dark')?'dark':'light');},init(){const v=localStorage.getItem("smarttown_theme");if(v==='dark')document.documentElement.classList.add('dark');}};
window.skins={list:[{id:'pine',label:'Pine Hollow',class:'skin-pine',town:'Pine Hollow',tagline:'Small town, big heart'},{id:'barn',label:'Red Barn',class:'skin-barn',town:'Red Barn',tagline:'Work hard. Help neighbors.'},{id:'willow',label:'Willow Creek',class:'skin-willow',town:'Willow Creek',tagline:'Quiet streets, clear service'}],apply(id){const s=this.list.find(x=>x.id===id)||this.list[0];document.documentElement.classList.remove('skin-pine','skin-barn','skin-willow');document.documentElement.classList.add(s.class);localStorage.setItem('smarttown_skin',s.id);const n=$('#town-name'),t=$('#town-tag');if(n)n.textContent=s.town;if(t)t.textContent=s.tagline;toast(`Theme: ${s.label}`);},init(){const saved=localStorage.getItem('smarttown_skin')||'pine';this.apply(saved);const sel=$('#skin-select');if(sel){sel.value=saved;sel.addEventListener('change',e=>this.apply(e.target.value));}}};
window.sales={toggle(){document.documentElement.classList.toggle('sales');localStorage.setItem('smarttown_sales',document.documentElement.classList.contains('sales')?'1':'0');},init(){const v=localStorage.getItem('smarttown_sales')==='1';if(v)document.documentElement.classList.add('sales');const btn=$('#sales');if(btn){btn.addEventListener('click',this.toggle);}}};
window.dataIO={key:'smarttown_sandbox_v4',export(){const blob=new Blob([localStorage.getItem(this.key)||'{}'],{type:'application/json'});const url=URL.createObjectURL(blob);const a=el('a',{href:url,download:'smarttown-demo-data.json'});document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);},import(file){const r=new FileReader();r.onload=()=>{try{localStorage.setItem(this.key,r.result);toast('Data imported');location.reload();}catch(e){toast('Import failed','warn');}};r.readAsText(file);}};
if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));}
